"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-07 07:15:23.878510
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_bundle",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_key", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("source_inventory", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("coverage_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("coverage_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("import_complete", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_table(
        "evidence_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bundle_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("parent_external_id", sa.Text(), nullable=True),
        sa.Column("author_id", sa.Text(), nullable=True),
        sa.Column("author_display_name", sa.Text(), nullable=True),
        sa.Column("participants", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["evidence_bundle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bundle_id", "source", "external_id"),
    )
    op.create_index(
        "idx_evidence_item_bundle_source_time",
        "evidence_item",
        ["bundle_id", "source", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "handoff",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_key", sa.Text(), nullable=False),
        sa.Column("bundle_id", sa.UUID(), nullable=False),
        sa.Column("expert_id", sa.Text(), nullable=False),
        sa.Column("successor_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["evidence_bundle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analysis",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("handoff_id", sa.UUID(), nullable=False),
        sa.Column("bundle_hash", sa.Text(), nullable=False),
        sa.Column("selected_engineer_id", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Text(), nullable=False),
        sa.Column("scoring_version", sa.Text(), nullable=False),
        sa.Column("extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status in ('pending','running','succeeded','failed')"),
        sa.ForeignKeyConstraint(
            ["handoff_id"],
            ["handoff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_analysis_handoff_created", "analysis", ["handoff_id", "created_at"], unique=False
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("handoff_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("target_revision", sa.Integer(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["handoff_id"],
            ["handoff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence_chunk",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_item_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=True),
        sa.Column("line_end", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_item_id"],
            ["evidence_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evidence_item_id", "ordinal"),
    )
    op.create_table(
        "operation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("handoff_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("result_type", sa.Text(), nullable=True),
        sa.Column("result_id", sa.UUID(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("state in ('pending','running','succeeded','failed','interrupted')"),
        sa.ForeignKeyConstraint(
            ["handoff_id"],
            ["handoff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "idempotency_key"),
    )
    op.create_index(
        "idx_operation_state_created", "operation", ["state", "created_at"], unique=False
    )
    op.create_table(
        "finding",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.UUID(), nullable=False),
        sa.Column("area_key", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("signal_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("review_priority", sa.SmallInteger(), nullable=True),
        sa.Column("evidence_confidence", sa.Text(), nullable=False),
        sa.Column("eligibility_status", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "eligibility_status in ('ranked','adequately_covered','not_prioritized','insufficient','review_required')"
        ),
        sa.CheckConstraint("evidence_confidence in ('high','medium','low')"),
        sa.CheckConstraint("status in ('candidate','confirmed','rejected','obsolete')"),
        sa.CheckConstraint("review_priority is null or review_priority between 0 and 100"),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_finding_analysis_priority",
        "finding",
        ["analysis_id", "eligibility_status", sa.literal_column("review_priority DESC NULLS LAST")],
        unique=False,
    )
    op.create_table(
        "knowledge_draft",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("author_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("finding_id"),
    )
    op.create_table(
        "knowledge_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("draft_revision", sa.Integer(), nullable=False),
        sa.Column("approved_content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expert_added_context", sa.Boolean(), nullable=False),
        sa.Column("approved_by", sa.Text(), nullable=False),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("supersedes_version_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_version_id"],
            ["knowledge_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("finding_id", "version_no"),
    )
    op.create_index(
        "idx_knowledge_version_finding_version",
        "knowledge_version",
        ["finding_id", "version_no"],
        unique=False,
    )
    op.create_table(
        "exercise",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("knowledge_version_id", sa.UUID(), nullable=False),
        sa.Column("scenario", sa.Text(), nullable=False),
        sa.Column("rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("approved_by", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status in ('draft','ready','obsolete')"),
        sa.ForeignKeyConstraint(
            ["knowledge_version_id"],
            ["knowledge_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attempt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("successor_id", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("assessment_status", sa.Text(), nullable=False),
        sa.Column("criterion_results", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("aggregate_result", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "aggregate_result is null or aggregate_result in ('demonstrated','partial','not_yet','review_required')"
        ),
        sa.CheckConstraint("assessment_status in ('pending','succeeded','failed')"),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercise.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_attempt_exercise_created", "attempt", ["exercise_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###

    # Immutability guards (FR-15, FR-21): approved knowledge and submitted answers
    # are append-only, enforced in the database, not only in application code.
    op.execute("""
        create or replace function sb_forbid_update() returns trigger as $$
        begin
          raise exception '% rows are immutable', TG_TABLE_NAME using errcode = 'P0001';
        end; $$ language plpgsql;
    """)
    op.execute(
        "create trigger knowledge_version_immutable before update or delete "
        "on knowledge_version for each row execute function sb_forbid_update();"
    )
    op.execute("""
        create or replace function sb_forbid_answer_change() returns trigger as $$
        begin
          if new.answer is distinct from old.answer or new.exercise_id is distinct from old.exercise_id
             or new.successor_id is distinct from old.successor_id then
            raise exception 'attempt answers are immutable' using errcode = 'P0001';
          end if;
          return new;
        end; $$ language plpgsql;
    """)
    op.execute(
        "create trigger attempt_answer_immutable before update on attempt "
        "for each row execute function sb_forbid_answer_change();"
    )
    op.execute(
        "create trigger audit_event_append_only before update or delete "
        "on audit_event for each row execute function sb_forbid_update();"
    )


def downgrade() -> None:
    op.execute("drop trigger if exists audit_event_append_only on audit_event")
    op.execute("drop trigger if exists attempt_answer_immutable on attempt")
    op.execute("drop trigger if exists knowledge_version_immutable on knowledge_version")
    op.execute("drop function if exists sb_forbid_answer_change()")
    op.execute("drop function if exists sb_forbid_update()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_attempt_exercise_created", table_name="attempt")
    op.drop_table("attempt")
    op.drop_table("exercise")
    op.drop_index("idx_knowledge_version_finding_version", table_name="knowledge_version")
    op.drop_table("knowledge_version")
    op.drop_table("knowledge_draft")
    op.drop_index("idx_finding_analysis_priority", table_name="finding")
    op.drop_table("finding")
    op.drop_index("idx_operation_state_created", table_name="operation")
    op.drop_table("operation")
    op.drop_table("evidence_chunk")
    op.drop_table("audit_event")
    op.drop_index("idx_analysis_handoff_created", table_name="analysis")
    op.drop_table("analysis")
    op.drop_table("handoff")
    op.drop_index("idx_evidence_item_bundle_source_time", table_name="evidence_item")
    op.drop_table("evidence_item")
    op.drop_table("evidence_bundle")
    # ### end Alembic commands ###
